name: recycleai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  device_apps: ^2.2.0
  path_provider: ^2.0.15
  tflite_flutter: ^0.10.1
  cupertino_icons: ^1.0.2
  camera: ^0.10.4
  gallery_saver: ^2.3.2
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  tuple: ^2.0.1
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^9.2.0
  fade_shimmer: ^2.2.0
  smooth_page_indicator: ^1.0.1
  flutter_expandable_fab: ^1.7.1
  persistent_header_adaptive: ^2.0.0
  flutter_native_splash: ^2.2.19
  google_sign_in: ^6.1.0
  get: 4.6.5
  get_storage: ^2.0.3
  shimmer: ^2.0.0
  http: ^0.13.6
  line_awesome_flutter: ^2.0.0
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  intl: ^0.18.1
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#70d065"
  image: assets/icons/splash.png
  # branding: assets/branding-development.png
  # color_dark: "#121212"
  # image_dark: assets/icons/ic_splash.png
  # branding_dark: assets/branding-development.png

  android_12:
    image: assets/icons/splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/icons/splash.png
    icon_background_color_dark: "#121212"

  web: false
